
services:
  frontend:
    build:
      context: ./ # Diret칩rio onde est치 o c칩digo do frontend
      dockerfile: Dockerfile # Caminho do Dockerfile para o frontend
    container_name: frontend-app
    ports:
      - "5173:5173" # Expondo a porta 3000 do container para a m치quina local
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
